### ISSUE TITLE
MJD out of range - prepfold

### ISSUE THREAD

**Issue by maddestpanda** [scottransom/presto#102]
When folding an artificial pulsar signal (created by injecting a pulse profile into a noise file), I get an error "MJD out of range" and in the next line "isets = 0". If I have tried changing the period and the MJD of these pulsars slightly in their .par files (since I am making pulsars with abnormally long periods for my project) and failed to correct the error. My pulsar periods (50, 70 , 100 seconds) are a significant amount of the observation time (600 seconds or 10 minutes) which I think may be responsible for the problem. Why does this error come up anyway? I could not find the source of this error in the source code for prepfold as well. Willing to provide any additional information as required.

**Comment by scottransom** [comment]
So you are folding with a parfile (and then automatically generating polycos)?  If so, this is a TEMPO error that I've seen before.  I don't understand what causes it either.  It seems to occur rarely, but might be related in your case to the long periods of the pulsars.  I'd recommend *not* folding with polycos if your pulse periods are that long, unless your fake datasets are many days in length.   If they are, you might need to edit the default parameters in polycos.c for how the polycos are generated...
