### ISSUE TITLE
Error when running `make` in $PRESTO/python

### ISSUE THREAD

**Issue by wcfiore** [scottransom/presto#103]
I'm getting a bunch of error messages when I run 'make' in $PRESTO/python, after successfully running 'make' in $PRESTO/src. In the attached text file, you'll find all the printed output that I get when I run 'make'.
[presto_error.txt](https://github.com/scottransom/presto/files/3452918/presto_error.txt)
I get a bunch of messages telling me to 'recompile with -fPIC'...I'm not sure what it wants me to recompile, I've tried recompiling pgplot with -fPIC in the flags but that does not solve the issue. Any help would be appreciated!

**Comment by scottransom** [comment]
Hey @wcfiore,

What OS are you running?  Compiling PGPLOT properly is a pain in the butt (because it has to be compiled and linked as a shared library, which is not trivial).  And this definitely seems like PGPLOT is not being properly compiled as a shared library.

If you are running Linux, I recommend installing it via the package for your distribution.  And on Macs, just use the MacPorts pgplot package.

Scott

**Comment by wcfiore** [comment]
Hi @scottransom, I'm trying to install presto at a user level on a CentOS linux machine. I had to compile PGPLOT myself, again on a user level; I've tried following the [instructions](http://www.astro.caltech.edu/~tjp/pgplot/install-unix.html) closely. I assume I have to edit the PGPLOT makefile in some way?

Thanks for the help,
Will

**Comment by wcfiore** [comment]
Never mind, I successfully compiled PGPLOT this time and was able to fix the other errors the PRESTO compiler threw at me. It's all good now!

**Comment by scottransom** [comment]
Excellent!

On August 1, 2019 8:59:20 AM EDT, William Fiore <notifications@github.com> wrote:
>Never mind, I successfully compiled PGPLOT this time and was able to
>fix the other errors the PRESTO compiler threw at me. It's all good
>now!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottransom/presto/issues/103#issuecomment-517276682

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
