### ISSUE TITLE
 error: ‘dind’ is predetermined ‘shared’ for ‘shared’

### ISSUE THREAD

**Issue by emmanuelfonseca** [scottransom/presto#107]
Hi @scottransom,

I ran into the following compilation issue when running `make` while trying to install `presto` on the Compute Canada `cedar` server:

`gcc -I/home/efonseca/projects/rrg-istairs-ad/software/src/presto/include -I/cvmfs/soft.computecanada.ca/nix/store/z52y2009k7njxsww9bgkbiqipl195lnh-glib-2.48.2-dev/include/glib-2.0 -I/cvmfs/soft.computecanada.ca/nix/store/qqqzb2sg02m9b526ns49jszk6svz8px3-glib-2.48.2/lib/glib-2.0/include -I/cvmfs/soft.computecanada.ca/nix/store/ys5ah1dn6gz5iwmrh7fr9jyi41c8rx2d-cfitsio-3.41/include -I -I/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/fftw/3.3.6/include -DUSEFFTW -DUSEMMAP -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -Wall -W -fPIC -O3 -ffast-math -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -fopenmp -I/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include  -c -o dispersion.o dispersion.c

dispersion.c: In function ‘dedisp_subbands’:

dispersion.c:195:58: error: ‘dind’ is predetermined ‘shared’ for ‘shared’

 #pragma omp parallel for default(none) private(jj) shared(sub,chan,numpts,dind)
                                                          ^
make: *** [<builtin>: dispersion.o] Error 1
`
This looks somewhat related to the latest commit that concerns shared-variable errors. Let me know if you'd like additional info.

- e.f.

**Comment by scottransom** [comment]
Well that's bizarre...  Hmm.  This has got to be a strange compiler version issue.  I'd recommend turning OpenMP of in the Makefile until I figure out the issue.

Scott


On November 11, 2019 4:06:08 PM PST, Emmanuel Fonseca <notifications@github.com> wrote:
>Hi @scottransom,>
>>
>I ran into the following compilation issue when running `make` while
>trying to install `presto` on the Compute Canada `cedar` server:>
>>
>`gcc
>-I/home/efonseca/projects/rrg-istairs-ad/software/src/presto/include
>-I/cvmfs/soft.computecanada.ca/nix/store/z52y2009k7njxsww9bgkbiqipl195lnh-glib-2.48.2-dev/include/glib-2.0
>-I/cvmfs/soft.computecanada.ca/nix/store/qqqzb2sg02m9b526ns49jszk6svz8px3-glib-2.48.2/lib/glib-2.0/include
>-I/cvmfs/soft.computecanada.ca/nix/store/ys5ah1dn6gz5iwmrh7fr9jyi41c8rx2d-cfitsio-3.41/include
>-I
>-I/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/fftw/3.3.6/include
>-DUSEFFTW -DUSEMMAP -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -Wall
>-W -fPIC -O3 -ffast-math -Wno-unused-result
>-Wno-unused-but-set-variable -Wno-unused-but-set-parameter -fopenmp
>-I/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/include  -c
>-o dispersion.o dispersion.c>
>dispersion.c: In function ‘dedisp_subbands’:>
>dispersion.c:195:58: error: ‘dind’ is predetermined ‘shared’ for
>‘shared’>
>#pragma omp parallel for default(none) private(jj)
>shared(sub,chan,numpts,dind)>
>                                                          ^>
>make: *** [<builtin>: dispersion.o] Error 1>
>`>
>This looks somewhat related to the latest commit that concerns
>shared-variable errors. Let me know if you'd like additional info.>
>>
>- e.f.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/scottransom/presto/issues/107

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Tommos0** [comment]
Having a similar problem, it's probably caused by the latest commit, see https://github.com/scottransom/presto/commit/32c9b9e9adc5ea3eae52ee23b3947633c1af5201#commitcomment-35913115

For me using HEAD~1 works.

**Comment by scottransom** [comment]
OK.  This is good to know.  Unfortunately, the changes that I made are *required* for GCC versions 8+ (or maybe 9+).  I'm not sure why, but it *seemed* to be a bug before, so I'm not sure why it is dying with the newest changes.  I'll try to look into this over the next couple days.

Meanwhile, yes, please either use HEAD~1 or set USEOPENMP to false in the Makefile.

**Comment by scottransom** [comment]
I just pushed up a fix (I think) for this based on this description:
https://www.gnu.org/software/gcc/gcc-9/porting_to.html
