### ISSUE TITLE
Polyco observatory issue

### ISSUE THREAD

**Issue by emmacarli** [scottransom/presto#113]
Good afternoon,
I'm not sure this is an issue with the software, it may stem from my misunderstanding of it!

I've added a custom observatory in TEMPO's obsys.dat:   
> 3573741.1      -269156.74      5258407.3      1  ACRE                -  AR  

I would like to fold topocentric observations taken at this observatory.

In the .inf file corresponding to my observation, I have input my observatory name (I have tried both "AR" and "ACRE") and observing frequency. The following fold command still defaults to barycentre for polyco generation. In the produced polyco headers, the observatory code is -1 and the observing frequency 0.
`prepfold -double -noxwin -par B0329+54.par timeseries.dat
`
Note, the par file also contains the observatory code "AR". I have tried without, too. 

To try and tackle this, I went to generate polycos with TEMPO on its own, and then input them in PRESTO. The polycos are generated correctly with:
`tempo  -ZOBS=AR -ZFREQ=407.5 -ZTOBS=4.1 -ZSTART=57969.1  -ZNCOEFF=15 -f B0329+54.par`

But when I try and input them into the fold, this is the result:
```
prepfold  -polycos polyco.dat -psr 0332+5434 -double -noxwin timeseries.dat  


        Pulsar Raw-Data Folding Search Routine
 Used for DM, Period, and P-dot tweaking of PSR candidates.
                 by Scott M. Ransom

Assuming the data are PRESTO time series of floats format...
Reading input data from 'timeseries.dat'.
Reading information from 'timeseries.inf'.

Folding a PSR_0332+5434 candidate.

Output data file is 'timeseries.pfd'.
Output plot file is 'timeseries.pfd.ps'.
Best profile is in  'timeseries.pfd.bestprof'.

Read 0 set(s) of polycos for PSR 0332+5434 at 57969.131833390893 (DM = 4.6704e-310)
MJD 57969.132 out of range (    0.000 to     0.000)
isets = 0
```
The output files are not created. The same happens with PINT-produced polycos.

Thanks for reading!
Best,
Emma

NB. The TEMPO -z command on its own crashes on my computer. I am currently trying different installs to solve this.

**Comment by paulray** [comment]
The name of the pulsar must be an EXACT match. Check your polycos.dat file and make sure the name is identical.

**Comment by paulray** [comment]
It can also help to add some print statements to PRESTO. I end up doing that a lot to diagnose problems with polyco creation. Probably we should make a PR to add some debugging prints to that part of the code since problems crop up there a lot.  Mainly you want to see the actual tempo command that it is running and any outputs from tempo.

**Comment by emmacarli** [comment]
> The name of the pulsar must be an EXACT match. Check your polycos.dat file and make sure the name is identical.

That was the issue in my second trial with the external polycos. Thank you!
Should I delete/close this issue, or do we leave it open for the debugging PR? As suggested, adding prints would probably explain why PRESTO is defaulting to barycentre - probably a mistake in usage.

**Comment by scottransom** [comment]
I think we can close the issue.  We probably shouldn't delete it (if that is even possible) for the reasons you say.  I'm happy to add some extra print statements (although dealing with TEMPO's output is tricky since it is called as a separate process).  If anyone wants to submit a pull request, I'll be happy to check it out and merge it.

**Comment by scottransom** [comment]
As an FYI, I just added a "-debug" flag to prepfold that will allow you to debug the TEMPO call.  It will keep all of the TEMPO output in the temporary directory and will also show you the exact command line used by TEMPO.

**Comment by emmacarli** [comment]
Thank you, that will be very helpful!
