### ISSUE TITLE
Tutorial problems

### ISSUE THREAD

**Issue by srcejon** [scottransom/presto#121]
Hi,

I'm following the tutorial at:

https://www.cv.nrao.edu/~sransom/GBT_Lband_PSR_cmd_history.txt

This command:

rfifind -nocompute -time 1.0 -freqsig 6.0 -mask -o Lband_rfifind.mask lband GBT_Lband_PSR.fil 

Results in:

rfifind: mandatory option `-o' missing

I assume it's supposed to be:

rfifind -nocompute -time 1.0 -freqsig 6.0 -mask Lband_rfifind.mask -o Lband GBT_Lband_PSR.fil 

Then:

cp $PRESTO/python/dedisp.py .

dedisp.py doesn't exist in that path. There are two versions: $PRESTO/tests/dedisp.py $PRESTO/examplescripts/dedisp.py, I presume the former should be used.

Likewise:

cp $PRESTO/python/ACCEL_sift.py .

Path seems to be $PRESTO/examplescripts/ACCEL_sift.py

Thanks.

**Comment by scottransom** [comment]
Thanks for this!  Should all be fixed with the latest commit 72b9f1a.  I also updated the text file on my website.
