### ISSUE TITLE
Presto 3 make issue

### ISSUE THREAD

**Issue by aweaver1fandm** [scottransom/presto#126]
I am trying to install PRESTO on Ubuntu.  I believe I have installed all the necessary dependencies and set all environment variables as described.  Make fails with the following error:

accel_utils.c:1648:71: error: ‘PROT_READ’ undeclared (first use in this function)
                (fcomplex *) mmap(0, sizeof(fcomplex) * obs->numbins, PROT_READ,
                                                                      ^~~~~~~~~
accel_utils.c:1649:35: error: ‘MAP_SHARED’ undeclared (first use in this function)
                                   MAP_SHARED, obs->mmap_file, 0);
                                   ^~~~~~~~~~
accel_utils.c:1650:29: error: ‘MAP_FAILED’ undeclared (first use in this function); did you mean ‘MAP_SHARED’?
             if (obs->fft == MAP_FAILED) {
                             ^~~~~~~~~~
                             MAP_SHARED

**Comment by aweaver1fandm** [comment]
So the problem appears to be with pgplot include and shared library in the Makefile.  I installed pgplot not by compiling from source but vi apt-get (apt-get install pgplot5) which the install file says is ok to do.  The INSTALL directions are then unclear about what to do with pgplot in the Makefile.  It says the PGPLOT directory should probably be set but there really isn't one in this case.  I ended up commenting out the PGPLOTINC  line in the Makefile

**PGPLOTINC = -I$(PGPLOT_DIR)**

I then changed the PGPLOTLINK line to be just
**PGPLOTLINK = -lcpgplot -lpgplot $(X11LINK) $(PNGLINK)**

And finally removed the **$(PGPLOTINC)** from the **CFLAGS =** line

Everything compiles and I am awaiting word from the researcher using this software that everything appears to be fine.

**Comment by scottransom** [comment]
Glad that you figured out what was causing that -- although it doesn't make sense at all that memmap flag errors should be related to the PGPLOT includes!

In general, the PGPLOT_DIR environment variable should be set to where the handful of required system PGPLOT files are located.  For Ubuntu (which is what I mostly use) that should be set to PGPLOT_DIR=/usr/lib/pgplot5

On Ubuntu, I don't need to even touch the Makefile.
.

**Comment by scottransom** [comment]
I just made the INSTALL clearer about PGPLOT_DIR when on Ubuntu (although it did mention setting that environment variable to /usr/lib/pgplot5 in the troubleshooting part at the bottom of the doc).
