### ISSUE TITLE
Error in chkfopen() : No such file or directory when running test_presto_python.py

### ISSUE THREAD

**Issue by 374365283** [scottransom/presto#127]
Hi @scottransom,
l'm installing presto on Centos. When l do "python tests/test_presto_python.py" , there is a problem:

>python tests/test_presto_python.py
Testing FFT stuff... success
Testing FFTW call... success
Testing tablesixstepfft call... success
Testing reading infiles... success
Testing writing infiles... success
Testing allocation and freeing of memory... success
Testing psrparams and orbitparams stuff... success
Testing spectralpower and spectralphase... success
Testing vector shifting / rotation... success
Testing orbit integration stuff... success
Testing Fourier response generation... success
Testing angle functions... success
Testing get_baryv (barycenter)...
Error in chkfopen(): No such file or directory
   path = 'resid2.tmp' 

What's more, when l followed the PRESTO_search_tutorial, l met the similar problem when doing: 

>prepfold -p 1.0 GBT_Lband_PSR.fil
Error in chkfopen(): No such file or directory
   path = 'resid2.tmp'

**Comment by scottransom** [comment]
That looks like you don't have TEMPO installed.  Is that correct?  If you install that, the barycenter stuff (which uses TEMPO) should work.

**Comment by 374365283** [comment]
Thanks, l installed TEMPO and it is solved now.

**Comment by scottransom** [comment]
Excellent.

**Comment by hamrus** [comment]
Hi @scottransom @374365283 ,
I have installed presto and tempo in ubuntu in a docker container (I think it should be installed) and when I run test_presto_python.py in the tests directory, I encounter the same problem, I don't understand what you are suggesting, can you elaborate on the solution?
<img width="308" alt="wechat_20240228181622" src="https://github.com/scottransom/presto/assets/102203971/394d3052-fbb9-4cf3-aa9a-0c94a3c1fd79">
<img width="978" alt="wechat_20240228185642" src="https://github.com/scottransom/presto/assets/102203971/628aa15e-38b1-4bb7-93a2-c7652f23052d">

**Comment by scottransom** [comment]
Is TEMPO actually installed in that Docker container?  i.e  Can you do `which tempo` from the command line and it points to the binary?  The compiled binary needs to be in your PATH.

**Comment by hamrus** [comment]
This docker  image was given to me by someone else, so I thought it was the image that was fine, then I reinstalled presto in my local environment and had the same problem, I finally found that ```tempo``` did not follow the ```README``` to ```prepare```and```make```, just only set in my ```PATH```, when I redo it, the problem was solved!
