### ISSUE TITLE
cands.sort(sifting.cmp_sigma) AttributeError: 'module' object has no attribute 'cmp_sigma'

### ISSUE THREAD

**Issue by LangQingjie** [scottransom/presto#130]
I was trying to run a code with sifting. but there is a error. I have imported: sifting
File "./pipeline.py", line 278, in ACCEL_sift
    cands.sort(sifting.cmp_sigma)
AttributeError: 'module' object has no attribute 'cmp_sigma'

**Comment by scottransom** [comment]
I think you are running into an issue that changed when switching from python 2 to python 3.  The cmp_sigma compare method cannot be used anymore.  I suspect that your code pipeline.py (which is not in PRESTO, right?) is still using that from before.

You need to change the .sort() method to use the key option.  Here are a couple examples from the current ACCEL_sift.py script in $PRESTO/examplescripts/

```
self.cands.sort(key=attrgetter('r')) # uses the attribute 'r', which is the Fourier frequency
```
and
```
matches.sort(key=attrgetter('sigma'), reverse=True)
```

If you are seeing that behavior from somewhere in the current PRESTO, please let me know.  But I think I changed all of those sorting issues many months ago.
