### ISSUE TITLE
Segmentation fault with DDplan.py file

### ISSUE THREAD

**Issue by mherreral** [scottransom/presto#131]
I was trying to test PRESTO, and I ended up with this situation running:
`DDplan.py -d 80 -n 96 -b 96.0 -t 0.000072 -f 1400.000000 -s 32 -o DDplan.ps`
The result of it was "sh: line 1: 31437 Segmentation fault      (core dumped) DDplan.py -d 80 -n 96 -b 96.0 -t 0.000072 -f 1400.000000 -s 32 -o DDplan.ps"

**Comment by scottransom** [comment]
Hmm.  That command runs just fine for me.  I suspect this is a library issue, perhaps with PGPLOT.

Are you able to run the following?

```
python $PRESTO/tests/test_presto_python.py 
Testing FFT stuff... success
Testing FFTW call... success
Testing tablesixstepfft call... success
Testing reading infiles... success
Testing writing infiles... success
Testing allocation and freeing of memory... success
Testing psrparams and orbitparams stuff... success
Testing spectralpower and spectralphase... success
Testing vector shifting / rotation... success
Testing orbit integration stuff... success
Testing Fourier response generation... success
Testing angle functions... success
Testing get_baryv (barycenter)... success
Testing simple folding code... success
```

If that crashes, please let me know what version of Python you are using.  And also please send me the results of "pip install ." (perhaps with --user) so I can see what is going on.

Also, are you able to run, for example, `prepfold` and get plots?

**Comment by mherreral** [comment]
This works properly:
`python $PRESTO/tests/test_presto_python.py`

The pip's result:
`pip install .
Processing /share/apps/presto/3.0.1/gcc-8.3.1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.11.0)
Requirement already satisfied: matplotlib in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (2.2.3)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.19.4)
Requirement already satisfied: future in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (0.18.2)
Requirement already satisfied: pyslalib in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.0.4)
Requirement already satisfied: astropy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (3.0.4)
Requirement already satisfied: scipy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.5.4)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.19.4)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.19.4)
Requirement already satisfied: cycler>=0.10 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->presto==3.0.1) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->presto==3.0.1) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->presto==3.0.1) (2.7.3)
Requirement already satisfied: pytz in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->presto==3.0.1) (2018.5)
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/anaconda3/lib/python3.7/site-packages (from matplotlib->presto==3.0.1) (1.0.1)
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.11.0)
Requirement already satisfied: setuptools in /root/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->presto==3.0.1) (40.2.0)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.19.4)
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.11.0)
Requirement already satisfied: numpy in /root/anaconda3/lib/python3.7/site-packages (from presto==3.0.1) (1.19.4)
Building wheels for collected packages: presto
  Building wheel for presto (PEP 517) ... done
  Created wheel for presto: filename=presto-3.0.1-cp37-cp37m-linux_x86_64.whl size=817596 sha256=43149a5aa49c0b40f7355959c78cb49b4b62dc56b670389d94b037b0c897a70a
  Stored in directory: /root/.cache/pip/wheels/f5/91/65/f0497f2b2ea4e2f50b5401137714153b0e889f6515d2997e37
Successfully built presto
Installing collected packages: presto
Successfully installed presto-3.0.1`

The prepfold output: 
'prepfold -n 64 -nsub 32 -dm 49.500000 -p 1.853673 GBT_Lband_PSR.fil -o Sband_DM49.50 -noxwin -nodmsearch


        Pulsar Raw-Data Folding Search Routine
 Used for DM, Period, and P-dot tweaking of PSR candidates.
                 by Scott M. Ransom

Assuming the data are SIGPROC filterbank format...
Reading SIGPROC filterbank data from 1 file:
  'GBT_Lband_PSR.fil'

    Number of files = 1
       Num of polns = 2 (summed)
  Center freq (MHz) = 1400
    Num of channels = 96
    Sample time (s) = 7.2e-05
     Spectra/subint = 2400
   Total points (N) = 531000
     Total time (s) = 38.232
     Clipping sigma = 6.000
   Invert the band? = False
          Byteswap? = False
     Remove zeroDM? = False

File  Start Spec   Samples     Padding        Start MJD
----  ----------  ----------  ----------  --------------------
1              0      531000           0  53010.48482638889254

Folding a 1853.67ms_Cand candidate.

Output data file is 'Sband_DM49.50_1853.67ms_Cand.pfd'.
Output plot file is 'Sband_DM49.50_1853.67ms_Cand.pfd.ps'.
Best profile is in  'Sband_DM49.50_1853.67ms_Cand.pfd.bestprof'.

Folding (topo) epoch  (MJD)  =  53010.484826388893
Folding (bary) epoch  (MJD)  =  53010.480956279986
Data pt duration (dt)   (s)  =  7.2e-05
Total number of data points  =  460800
Number of profile bins       =  64
Folding period          (s)  =  1.853673
Folding frequency      (hz)  =  0.539469474929

WARNING:  The pulse period is close to the duration of a folding
  sub-interval.  This may cause artifacts in the plot and/or excessive
  loss of data during the fold.  I recommend re-running with -npart set
  to a significantly smaller value than the current value of 64.
True starting fraction       =  0

Generating barycentric corrections...
The average topocentric velocity is -5.69726e-05 (units of c).

Barycentric folding frequency    (hz)  =  0.539469474929
Barycentric folding f-dot      (hz/s)  =  0
Barycentric folding f-dotdot (hz/s^2)  =  0
Topocentric folding frequency    (hz)  =  0.539500208242
Topocentric folding f-dot      (hz/s)  =  5.1981638e-11
Topocentric folding f-dotdot (hz/s^2)  =  -6.6376118e-13

Will search 1 DMs from 0.000 to 9830.175 (ddm = 25.5329)

Starting work on 'GBT_Lband_PSR.fil'...

  Folded 460800 points of 460800

Optimizing...

  Searching 1 DMs, 257 periods, and 257 p-dots...
     (66049 total trials)
  Amount Complete = 100%  Done searching.

Maximum reduced chi-squared found  =  24.99342
Best DM     (pc cm^-3)  =  51.0658
Best topocentric period        (s)  =   1.91371(18)
Best topocentric p-dot       (s/s)  =  -0.000390(41)
Best topocentric p-dotdot  (s/s^2)  =  0.0(8.1)x10^-6
Best barycentric period        (s)  =   1.91382(18)
Best barycentric p-dot       (s/s)  =  -0.000390(41)
Best barycentric p-dotdot  (s/s^2)  =   0.2(8.1)x10^-6

Making plots.

Effective number of DOF = 60.48
Off-pulse Reduced chi^2 correction factor = 0.88
sh: pstoimg: command not found
Error running pstoimg in prepfold_plot(): Success

Done.'

is this line "Error running pstoimg in prepfold_plot(): Success" usual?

**Comment by mherreral** [comment]
When I run the DD command above with python2.7, it works, and there's no segfault

**Comment by scottransom** [comment]
That's really bizarre.  So you only get the segfault with Python 3 with DDplan.py?  Does it segfault if you omit the "-o" ouput file option and just use an X-window?

As for the pstoimg warning/error, that isn't a killer.  But if you have latexthtml installed, pstoimg makes a nice .png file as well as the .ps file automatically.
