### ISSUE TITLE
Access to P/Pdot uncertainties through python pfd interface

### ISSUE THREAD

**Issue by dlakaplan** [scottransom/presto#147]
I am trying to access the `prepfold` P and Plot uncertainties through the python interface (loading in a `pfd` file).  I don't see those values: I see `bary_p1` and `bary_p2` but nothing obvious that would have the uncertainties.  Are they there?  If not, is it possible to add them (note that I am using v3, so if this is fixed in v4 please forgive me).

**Comment by scottransom** [comment]
As long as the bestprof file is available as well, those values are available in x.bestprof.p[012]err, where x is the object where you loaded the .pfd file.  Those values are from `fold_errors()` in fold.c.

**Comment by dlakaplan** [comment]
OK, I thought it might just be in the pfd file.  I'll get the bestprofs too

**Comment by scottransom** [comment]
Note that you can regenerate the .bestprof by simply running `show_pfd`.  Then load the .pdf using the `prepfold.py` stuff, and in the .pfd object there will be a .bestprof object with the error attributes that I mentioned.
