### ISSUE TITLE
makezaplist.py: No module named presto 

### ISSUE THREAD

**Issue by davidepelliciari** [scottransom/presto#153]
Hi everyone, i'm new in PRESTO and I'm following the tutorial in order to learn how to use it.
I installed PRESTO with success (apparently :D) but I'm stucked at the following line of code:

`makezaplist.py Lband.birds`

When I type this command I receive this error line:

```
from presto.presto import read_inffile, binary_velocity, psrepoch
ImportError: No module named presto
```

I already created the `.birds` file, and also commands like `readfile`, `rfifind`, `explorefft`, `exploredat`, `explorefft` and others are working fine.  I also tried to check if `presto` module can be imported (by hand) by typing `python` and then `import presto` (I checked also for python3) and all works fine. 
Someone can help?

**Comment by paulray** [comment]
You can't use Python 2.7 with modern presto. Make sure that your default "python" is python 3.7 or above.  Also make sure your "pip" corresponds to that same version of python, and that you have done `cd $PRESTO; pip install .` to get it installed.
If all that is true, it should work.  My guess is that `makezaplist.py` is getting started with a version of python that is old or not the one you installed the presto python module with.

**Comment by scottransom** [comment]
It is also possible that the C-compiled portion of the python installation failed.  Can you do `import presto.presto`?  If not, then I think that is likely what happened.  In that case, please remove the "build" directory from $PRESTO and then do "pip install ." and attach all of the output.

**Comment by davidepelliciari** [comment]
> It is also possible that the C-compiled portion of the python installation failed. Can you do `import presto.presto`? If not, then I think that is likely what happened. In that case, please remove the "build" directory from $PRESTO and then do "pip install ." and attach all of the output.

I've got no "build" directory in $PRESTO.. Anyway I re-installed presto with an updated version of python, now `pip install .` works fine, but `makezaplist.py Lband.birds` do not..

**Comment by scottransom** [comment]
Are you going to post or send me the install output?  And also, what happens when you run `python tests/test_presto_python.py`?

**Comment by davidepelliciari** [comment]
> Are you going to post or send me the install output? And also, what happens when you run `python tests/test_presto_python.py`?

Excuse me but what install output? (from what command?) 
When I run`python tests/test_prest_python.py`:

```
  File "test_presto_python.py", line 3, in <module>
    from presto import presto
ImportError: cannot import name presto
```

Excuse me for the lost of time..

**Comment by scottransom** [comment]
Right.  So this shows that the python modules are not being installed correctly.  So I need to see what you get when you type "pip install ." from $PRESTO.

And I'm assuming that you have compiled all of the regular parts of PRESTO?  i.e. do you have dynamic library files in $PRESTO/lib?

**Comment by paulray** [comment]
Also give the output of `which python` and `which pip` and `python --version`

**Comment by davidepelliciari** [comment]
`which python` = /usr/bin/python (I've got also installed the 3.7 version but i don't know how to change the standard python..)
`which pip` = /home/davide/.local/bin//pip

`pip instsall .` from $PRESTO:

`Defaulting` to user installation because normal site-packages is not writeable
Processing /home/davide/presto
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: matplotlib in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (3.3.2)
Requirement already satisfied: astropy in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (4.1)
Requirement already satisfied: future in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (0.18.2)
Requirement already satisfied: six in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (1.15.0)
Requirement already satisfied: scipy in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (1.5.2)
Requirement already satisfied: pyslalib in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (1.0.4)
Requirement already satisfied: numpy in /home/davide/.local/lib/python3.6/site-packages (from presto==4.0) (1.19.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (7.2.0)
Requirement already satisfied: certifi>=2020.06.20 in /home/davide/.local/lib/python3.6/site-packages (from matplotlib->presto==4.0) (2020.6.20)
Building wheels for collected packages: presto
  Building wheel for presto (PEP 517) ... done
  Created wheel for presto: filename=presto-4.0-cp36-cp36m-linux_x86_64.whl size=716159 sha256=993befe1a7c0f42fc71d0468ed52e78737c53621b57352001a8e5a11fced3c90
  Stored in directory: /tmp/pip-ephem-wheel-cache-rlma2nl3/wheels/a9/ae/fd/f142d08a5a770bc657c726ec95c47371d7f5e7110a2babce26
Successfully built presto
Installing collected packages: presto
  Attempting uninstall: presto
    Found existing installation: presto 4.0
    Uninstalling presto-4.0:
      Successfully uninstalled presto-4.0
Successfully installed presto-4.0`

**Comment by scottransom** [comment]
And did you build all of the C code?  i.e. can you run `prepfold`?  And are there dynamic libraries in $PRESTO/lib?  That stuff is *crucial* for the python programs to work.

**Comment by paulray** [comment]
Also try `pip --version` and what OS are you using?
I'd be careful about multiple versions of python. Sometimes you may be calling your /usr/bin/python (which it seems is 3.6) and other times you may be using your python3.7 (wherever you put that).

**Comment by paulray** [comment]
> Also try `pip --version` and what OS are you using?
> I'd be careful about multiple versions of python. Sometimes you may be calling your /usr/bin/python (which it seems is 3.6) and other times you may be using your python3.7 (wherever you put that).

Ooops, I was wrong there. Your /usr/bin/python is 2.7. That is not good. You want to make sure you are running python 3.7 for use with presto and that your pip corresponds to 3.7, not your python2 system python.

**Comment by davidepelliciari** [comment]
I can run prepfold (gives me the informations about that command). 

`pip --version`=` pip 21.2.4 from /home/davide/.local/lib/python3.6/site-packages/pip (python 3.6)`

In $PRESTO/lib there are these files:

```
a2x.ps       fftw_wisdom.txt  libsla.so         pulsars.cat
a2xshell.ps  goodfactors.txt  parkes_birds.txt
aliases.txt  libpresto.so     psr_catalog.txt
```
I know that I have to run presto with python3.7 and I already have it, but how do I make python point towards python3.7? (in order to have python3.7 as a standard)
I searched also on the internet but I found no working helps (and I don't have as many skills to be able to edit python, surely)

Again, sorry for the waste of time and thanks for the many replies

**Comment by scottransom** [comment]
Not sure if you meant to close this or not, but sounds like you have had several python version issues.  I'd recommend using a python virtual environment, which you have to activate.  That sets things up so that your python, pip, and all installed libraries are consistent.  You would definitely need to re-install PRESTO's python stuff into that, though.

**Comment by paulray** [comment]
Concur. Using a virtualenv or a conda environment will help encapsulate things

**Comment by davidepelliciari** [comment]
Thanks for the many helps, now PRESTO is working fine and I completed the tutorial!
