### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by davidepelliciari** [scottransom/presto#154]
Hello, I'm analyzing Parkes_70cm_PSR.fits data (downloaded from the tutorial page) and I ran into the following error when I tried to do python `python3.6 ACCEL_sift.py > cands.txt `:

```
Traceback (most recent call last):
  File "ACCEL_sift.py", line 63, in <module>
    cands = sifting.read_candidates(candfiles)
  File "/home/davide/.local/lib/python3.6/site-packages/presto/sifting.py", line 1198, in read_candidates
    curr_candlist = candlist_from_candfile(filenm, trackbad=track, trackdupes=track)
  File "/home/davide/.local/lib/python3.6/site-packages/presto/sifting.py", line 1113, in candlist_from_candfile
    DMstr = DM_re.search(filename).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

This is my ACCEL_sift.py file:

```
# glob for ACCEL files
globaccel = "*ACCEL_*0"
# glob for .inf files
globinf = "Lband_DM*.inf"
# In how many DMs must a candidate be detected to be considered "good"
min_num_DMs = 2
# Lowest DM to consider as a "real" pulsar
low_DM_cutoff = 2.0
# Ignore candidates with a sigma (from incoherent power summation) less than this
sifting.sigma_threshold = 4.0
# Ignore candidates with a coherent power less than this
sifting.c_pow_threshold = 100.0

# If the birds file works well, the following shouldn't
# be needed at all...  If they are, add tuples with the bad
# values and their errors.
#                (ms, err)
sifting.known_birds_p = []
#                (Hz, err)
sifting.known_birds_f = []

# The following are all defined in the sifting module.
# But if we want to override them, uncomment and do it here.
# You shouldn't need to adjust them for most searches, though.

# How close a candidate has to be to another candidate to
# consider it the same candidate (in Fourier bins)
sifting.r_err = 1.1
# Shortest period candidates to consider (s)
sifting.short_period = 0.0005
# Longest period candidates to consider (s)
sifting.long_period = 15.0
# Ignore any candidates where at least one harmonic does exceed this power
sifting.harm_pow_cutoff = 8.0

#--------------------------------------------------------------
```

While this is the typical name of my files: 

```
Lband_DM334.20_ACCEL_0
Lband_DM334.20_ACCEL_0.cand
Lband_DM334.20.dat
Lband_DM334.20.fft
Lband_DM334.20.inf
```

Consider that I don't encounter any errors like this  when analyzing the `GBT_Lband_PSR.fil` .. someone can help?

**Comment by scottransom** [comment]
The first thing to check is that you don't have any "extra" files in your directory that are messing up the "globbing" in ACCEL_sift.py.  That can *definitely* lead to errors like this.

In your case, make sure that "ls *ACCEL_*0" and "ls Lband_DM*.inf" each return the same number of files (those are the two globbing lines used).  I suspect that you have one or more extra `.inf` files that don't have the correct filename structure.

**Comment by davidepelliciari** [comment]
Yes, you're right.. Some DM files do not have any corresponding ACCEL_0.. why this is happening and how should I proceed? Should I follow a better de-dispersion plan?

**Comment by scottransom** [comment]
Usually it happens because people do test dedispersions or whatever in their working directories and forget that those "extra" files are in there.  You can fix it by simply copying the correct .inf and ACCEL files to a different directory and then running ACCEL_sift.py there.  Note that it is OK if there are some extra .inf files, as if accelsearch doesn't find any candidates, it doesn't output any ACCEL files.  However, all of the .inf files that are there, have to be formatted correctly!  (for instance, they have to have DM and a number for the DM in their filenames!)

**Comment by davidepelliciari** [comment]
Problem solved, thank you very much Scott.
