### ISSUE TITLE
Who's using the classic branch?

### ISSUE THREAD

**Issue by astrogewgaw** [scottransom/presto#155]
<div align="justify">

This is a _question,_ rather than an issue or a feature request: is PRESTO's _classic_ branch being used by people? I ask this out of curiosity, since I have been thinking of adding support for more formats in the [**priwo**](https://github.com/astrogewgaw/priwo) package, and I wanted to know if they are any outdated formats that I should add support for. Is there still some useful data stored in the formats that are now only supported by the _classic_ branch?

</div>

**Comment by scottransom** [comment]
Good question.  I think some GMRT folks have been using it to process some old (and new) GMRT format data.  And there is certainly a bunch of old BCPM and Spigot data around that people *might* want to process.  However, at least the BCPM and Spigot data is convertable by DSPSR.  So I really doubt that many people are using it.  And therefore I'm not sure how useful it would be to have in `priwo`.

**Comment by astrogewgaw** [comment]
<div align="justify">

@scottransom Thanks for the quick reply 😁 ! Yup, adding support for formats that can be converted to newer formats anyways is probably not the best use of my time. I think I will focus on the formats currently in use. I have already added support for **SIGPROC filterbank** files, and am working on **PSRFITS** support (both _fold_ and _search_ modes, using **astropy**). Are there any other formats that are widely used in the community?

</div>

**Comment by scottransom** [comment]
Not really.  Those two are by far the most common ones.

**Comment by astrogewgaw** [comment]
I thought so. I will be closing the issue then 👍🏾 . Thanks for answering all of my questions 😁 !
