### ISSUE TITLE
Using prepsubband for only a fraction of a dataset 

### ISSUE THREAD

**Issue by k-perez** [scottransom/presto#172]
Hi Scott,

I have a long filterbank file, and am wondering what is the best way, if any, to analyze only a chunk of the data. While `prepfold` has the `-start` and `-end `options, `prepdata` and `prepsubband` are missing the `-end `option. 

Thank-you

**Comment by scottransom** [comment]
You can get the same effect as `-end` by specifying `-numout` (and that is "more precise" since the resulting file size can be tuned to be good for FFTs, for example.

**Comment by k-perez** [comment]
Ah, I see. So `-numout` will specify the number of points after whichever `-start` point I use? Example: `-start 0.25 -numout 4000` will take the 4000 points starting at the quarter point of the data?

**Comment by scottransom** [comment]
Exactly.
