### ISSUE TITLE
Build issue with pulsestack.py

### ISSUE THREAD

**Issue by aweaver1fandm** [scottransom/presto#174]
I was troubleshooting another issue when I found 4 indent errors with pulsestack.py.  If you install following your directions (namely pip install .) you won't see the error, but doing pip install -v . shows them.  The 4 lines indented incorrectly are 784, 955, 966, and 991.  When I view the file on GitHub you can see the indentations are off as well

**Comment by scottransom** [comment]
Thanks for this.  I don't think that I've ever used that code!  I'm pretty sure that I fixed the indentation problems, and then I ran `black` on the file for good measure.  Please let me know if it works for you (although maybe you aren't running it either!).

**Comment by aweaver1fandm** [comment]
Indentation problems look to be fixed
