### ISSUE TITLE
undefined symbol: _gfortran_st_close

### ISSUE THREAD

**Issue by AdamLusvith** [scottransom/presto#180]
Hi scott, Sorry to bother you again, after I successfully installed presto to my environment, I try to run test_presto_python.py to check whether my presto is fine. But I got an issue:

(presto) [adam@localhost tests]$ python test_presto_python.py
Traceback (most recent call last):
  File "/home/adam/astrosoft/presto/tests/test_presto_python.py", line 3, in <module>
    from presto import presto
  File "/home/adam/anaconda3/envs/presto/lib/python3.10/site-packages/presto/presto/__init__.py", line 8, in <module>
    from presto import Pgplot
  File "/home/adam/anaconda3/envs/presto/lib/python3.10/site-packages/presto/Pgplot.py", line 22, in <module>
    from presto import ppgplot
  File "/home/adam/anaconda3/envs/presto/lib/python3.10/site-packages/presto/ppgplot/__init__.py", line 1, in <module>
    from _ppgplot import *
ImportError: /home/adam/astrosoft/pgplot/libpgplot.so: undefined symbol: _gfortran_st_close

It looks like there is a problem with pgplot, but I installed pgplot according to INSTALL.md.  set `PGPLOT_DIR` environment  variable and edited the setup.py . Maybe I made a mistake somewhere.

**Comment by scottransom** [comment]
This happens on some systems and I don't understand why.  In `setup.py`, note the following:
```
# Note:  you might need to add "gfortran" to the following list if 
# you see errors relating to missing "g" functions....
ppgplot_libraries = ["cpgplot", "pgplot", "X11", "png", "m"]
```
Try adding "gfortran" to that list.

**Comment by AdamLusvith** [comment]
> This happens on some systems and I don't understand why. In `setup.py`, note the following:
> 
> ```
> # Note:  you might need to add "gfortran" to the following list if 
> # you see errors relating to missing "g" functions....
> ppgplot_libraries = ["cpgplot", "pgplot", "X11", "png", "m"]
> ```
> 
> Try adding "gfortran" to that list.

Yeah, Now my results are all success! Thanks for your help and patience!
