### ISSUE TITLE
Doc fix

### ISSUE THREAD

**Issue by paulray** [scottransom/presto#195]
https://github.com/scottransom/presto/blob/24a4f31f48f63c568059dc215840d91d38c4f6f2/INSTALL.md?plain=1#L58

After this line you should say that fftw_wisdom.txt needs to be copied from $PRESTO/build/src to $PRESTO/lib

**Comment by paulray** [comment]
Also in INSTALL, I'd say somewhere that all the binaries (compiled and python) will be installed in $PREFIX/bin and libpresto.(so or dylib) will be installed in $PREFIX/lib.  Just for clarity.

**Comment by scottransom** [comment]
Done in v5.0.0  Thanks!
