### ISSUE TITLE
Feature request related to plotting

### ISSUE THREAD

**Issue by aweaver1fandm** [scottransom/presto#196]
I have a researcher who has been using presto for many years now.  We currently run the analyses on a high performance compute cluster using a job scheduler to submit/run the jobs.  There is a point in many of his jobs where prepfold_plot gets called just to produce an output file (possibly in png format not sure).  The problem is we aren't able to have X11 going for the cluster job once it's submitted and so we can't run pgplot with xserver to do it's voodoo.

Would it be possible in such cases, where essentially we really don't need a GUI for viewing purposes to still produce the output plots in some other fashion (e.g., matplotlib)?

**Comment by paulray** [comment]
You can just specify `-noxwin` to your prepfold command, if I'm understanding your question correctly.

**Comment by aweaver1fandm** [comment]
That will likely be the answer. We'll give it a shot

**Comment by aweaver1fandm** [comment]
I just doubled checked and we are already doing -noxwin for prepfold calls and it still doesn't seem to like it

**Comment by aweaver1fandm** [comment]
Here is the error we get even running with noxwin

Error: "/opt/apps/spack/netpbm-10.73.43-u7pxw3h/bin/pnmflip -cw < /tmp/p769858.pnm| 
/opt/apps/spack/netpbm-10.73.43-u7pxw3h/bin/pnmquant 256 | 
/opt/apps/spack/netpbm-10.73.43-u7pxw3h/bin/pnmtopng  > S00611_4_DM61.00_ACCEL_50_ACCEL_Cand_1.pfd.png" failed: 
Error running pstoimg in prepfold_plot(): No such device or address

**Comment by paulray** [comment]
Ah I see. This really isn't a presto thing, so `-noxwin` won't help. After presto successfully(?) generates the .ps prepfold plot, it runs pstoimg to convert the .ps file to a .png using the pnm utilities.  Try running pstoimg on its own on one of the cluster nodes. If that fails, then you need to get that working, but I'm not sure what that will take. Perhaps something with your DISPLAY envariable or something like that?

**Comment by aweaver1fandm** [comment]
Paul,

Thanks, you basically confirmed what I thought.  Mostly I was wondering if
it might be possible to generate the plots using matplotlib instead of
converting things through pstoimg and it sounds like that may not be a
practical solution

**Comment by paulray** [comment]
Yes, directly generating the plots in a more modern format than .ps would be good (e.g. PDF or PNG), but they are generated in C code that calls PGPLOT to make the plots. This would require some effort to update.

**Comment by scottransom** [comment]
PGPLOT cannot generate .pdf output.  It *can* directly output .png, however, it does not use anti-aliasing, nor can you (easily?) change the resolution, and so the plots look terrible.  That's why I output .ps and then (if latex2html is availble) use it to convert nicely to .png.

@aweaver1fandm are the output .ps plots being generated?  I suspect that they are, and if so, this error really is effectively a warning that latex2html is not available on the compute nodes.  That means that you can always re-generate the .pngs (if wanted) post-facto by running `pfd2png.sh` on the .pfd.ps files on a machine that hast latex2html installed.

If the output .ps files are *not* getting generated, then this is a real issue and an error that I have not seen before.

**Comment by aweaver1fandm** [comment]
I'll double check that the ps files are getting generated

**Comment by aweaver1fandm** [comment]
The ps files are being written.  I removed the latex2html packages so we
aren't seeing the errors and the researcher will continue to create the png
version of the plots offline  after doing runs on the cluster.  That is
what they were doing before.  Just thought it wouldn't hurt to check and
see what if anything could be done to generate them in the course of the
cluster calculations.  Thank you for all your feedback
