### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by issaeghdami** [scottransom/presto#48]
Hi
I have installed presto just like the INSTALL file said (I guess) but when installation finished (without error), presto's commands  are not recogonized in terminal! here is a screenshot:
http://tinypic.com/r/161x34x/8

what's wrong?

**Comment by paulray** [comment]
PRESTO installs the binary executables in $PRESTO/bin
Make sure you have that directory in your path, and do "rehash" if you are using csh or tcsh.

**Comment by issaeghdami** [comment]
yes they are there but also they are not recognized :(  
as you can see, I have done rehash :
http://tinypic.com/r/33jtwk5/8

**Comment by paulray** [comment]
Try running them directly like "./rfifind".  Also, do an "ls -l" in $PRESTO/bin and make sure the executables are there and are executable.

**Comment by issaeghdami** [comment]
Thank you for your responding. I don't know what to do! :
http://tinypic.com/r/s6ixrl/8

 Maybe I have edited the Makefile incorrectly
can someone upload a worked Makefile here? tnx

**Comment by paulray** [comment]
First, you should not be running anything as root on your machine.  You should build and install PRESTO as your normal user. You should go to the src directory as root and do a "make clean", then go back to your normal user and re-make everything.

Second, it is just not finding the shared library.  Make sure that $PRESTO/lib is in your LD_LIBRARY_PATH.  You can use "ldd" on an executable to see what libraries it is looking for and where it is finding them.

**Comment by issaeghdami** [comment]
Finally ! solved 
in bashrc I had this line :

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SOFTWARE_DIR/lib:\
$SOFTWARE_DIR/pgplot_build:$SOFTWARE_DIR/presto/lib

adding this line made everything ok ! :
export PATH=$PATH:$SOFTWARE_DIR/bin:$SOFTWARE_DIR/presto/bin

**Comment by scottransom** [comment]
Thanks for helping out, @paulray.

Be advised that you will need $PRESTO/lib/python in your PYTHONPATH if you want to use the python functionality as well.

**Comment by issaeghdami** [comment]
Thank you guys :)

**Comment by issaeghdami** [comment]
I have two more questions:
1) Can presto use tempo 2 instead of tempo ? 
2)  "readfile" is working for sample GBT..... .fil file but when I'm using it for openning a ".sf" file this error appears: 
ERROR: Mismatch in the version of the fitsio.h include file used to build
the CFITSIO library, and the version included by the application program:
   Version used to build the CFITSIO library   = 3.340000
   Version included by the application program = -0.114275
Segmentation fault (core dumped)
-----------------
negative version?! 
I'm using tempo 2 and psrchive and oppening *.rf and *.tim files so Cfitsio is installed !

**Comment by scottransom** [comment]
For question 1:  No, not currently.  And that's primarily because I rarely use TEMPO2.  Adding that capability should be fairly straightforward, though.  I'd be happy to accept a patch or pull-request!  ;-)

As for question 2, that is because you have 2 installations of CFITSIO on your machine.  And when things were compiled, the header for one version was found and used (via the -I include flags) but you are linking to a different version (via the -L flags or LD_LIBRARY_PATH).  Forcing the use of a consistent version with the flags or the LD_LIBRARY_PATH is how you solve that.

**Comment by issaeghdami** [comment]
Thank you sir

**Comment by issaeghdami** [comment]
I have installed and used PGPLOT in PSRCHIVE but in presto when I tried :
" exploredat Lband_topo_DM0.00.dat "
everything is good until opening pgplot! 

Examining Mystery_PSR data from 'Lband_topo_DM0.00.dat'.
 %PGPLOT, Unrecognized device type
 %PGPLOT, Invalid device specification: /XWIN

although, from rfifind command, a "PS" output file is plotted and it shows that pgplot is working.

**Comment by paulray** [comment]
This is not a PRESTO issue, but a PGPLOT one.  You need to set your environment variable PGPLOT_DEV to a device that was included in your build of PGPLOT.  See the PGPLOT installation instructions for more info.  Normally /XS and /XWIN are always included.  An interactive X11 driver for PGPLOT is required for interactive programs like exploredat.
