### ISSUE TITLE
prepfold is not multiprocessing safe

### ISSUE THREAD

**Issue by paulray** [scottransom/presto#49]
It would be nice to be able to run many instances of prepfold at the same time, e.g.  using multiprocessing.Pool() in Python. However, this is not safe and ends up crashing because the polycos that are generated by each instance stomp on each other. It would be nice if unique tempfiles were used to prevent this from happening.

**Comment by scottransom** [comment]
yeah....  this has been on the ToDo list forever....  Pull-requests welcome!  (I even think that fold_psrfits does this correctly, so we could probably just steal the code from there...)

**Comment by scottransom** [comment]
I just implemented and pushed this up as well.  Should be good...  But testing with your script would be excellent, @paulray
