### ISSUE TITLE
packaging up presto and python files

### ISSUE THREAD

**Issue by gijzelaerr** [scottransom/presto#69]
I'm working on a radio astronomy software distribution based on debian/ubuntu named kern. Packaging up astronomy software should make the life of many astronomers much easier and will save a lot of time and agony all around the world. Since presto is a often used software package we decided to add it to kern. More info can be found here: http://kernsuite.info/. If the package is stable enough it may end up in Debian/ubuntu itself, could be already for the next Ubuntu release.

The presto package already works, but there is a problem with the python files. Ideally the presto python files would be located in a presto python module which would be then installed in the python. This requires a bit of restructuring of the python files. 

Would it be an idea to do this? Forcing a user to set up a `PYTHONPATH` works, but it is not really the right way to do things. If we can restructure the python files in presto it would simplify the setup procedure a bit more, makes it possible to install it in a virtualenv and maybe even trough pypi using pip.

**Comment by scottransom** [comment]
Sorry for the delay... I've been traveling and am slowly digging myself out of email backlog.  Yeah, I think this sounds like a pretty good idea.  Have you (or anyone else?) taken a look as to how much work this would require?

**Comment by gijzelaerr** [comment]
hi @scottransom, no problem thanks for replying.

I made the package now in such a way that all python files are installed into a presto package inside the default search path. Since some python files in presto expect the presto python modules to be in the root of the python path, one needs to manually add the presto python package to the  python root. The long term and right solution here is to modify the presto code to load the modules from the presto module, not the root. This is the 'pythonic' way to do things. 

I'm no presto expert, but I asked somebody to try to get the presto package working. It looks like everything works, as long as you manually set the python path. 

If we modify the Python code, the presto package would just run out of the box. I think this is also a good first step into cleanup presto up, I think the installation procedure can be simplified.  Problem is that if we install the presto python modules into a presto module (which is the right thing to do) exciting scripts will fail for people. But this is something we could write into a changelog which is bundles with a release.

If you want I can help you out modifying the code. But if we do I strongly recommend you start introducing versioning to this presto repository. I only see one 0.2 release from 2.5 years ago. I suggest you just make a release now, and we make a release after the Python  modifications.

**Comment by gijzelaerr** [comment]
We now patch the original source to use the presto package:

https://github.com/kernsuite-debian/presto/blob/master/debian/patches/presto_package

**Comment by gijzelaerr** [comment]
hi @scottransom is it an idea to try to pick this up again? the KERN packages have been used for a while now, and moving a presto python code into a presto python module is a requirement to package up presto properly. I'm shipping a patched presto based on a module and as far as I know it works quite well, but the changes get out of sync over time.

**Comment by scottransom** [comment]
hi @gijzelaerr   Yeah, I think this makes sense.  I'm in the middle of a big PR to get PRESTO working in Python2 and Python3 (see #90 ), and hopefully we can make this a part of that big change.  Do you know if your changes will work with Py3?

**Comment by gijzelaerr** [comment]
hi @scottransom my changes definitely will work with Python3, and i'll fix the python3 issues where I'll encounter them. I'm going to sit down for this next week Wednesday for a day. In what time zone are you? Maybe good if I can ask you some questions during the refactor?

**Comment by scottransom** [comment]
I'm in the US Eastern.  So we are currently 4 hours behind UTC.  Am happy to handle questions about the refactor.

**Comment by gijzelaerr** [comment]
ok well, I'll just get started on Wednesday and then around the time you wake up, I might some questions.

my goals are:
* move all python code to a presto module
* make the installation procedure more pythonic
* improve/maintain python3 support while keeping python 2 support.

If there is time left I will:
* examine the code using static code analysis and try to find/fix bugs.

**Comment by gijzelaerr** [comment]
I see now you have already been very busy with adding python3 support in the python3 branch. Maybe best to merge that in first. What is the status of this work now?

**Comment by gijzelaerr** [comment]
ah well i'll base it on the python3 branch then.

**Comment by gijzelaerr** [comment]
this is implemented in this PR https://github.com/scottransom/presto/pull/94

**Comment by gijzelaerr** [comment]
this issue has been resolved! Thanks!
