### ISSUE TITLE
how to get a .birds file

### ISSUE THREAD

**Issue by tauriel27** [scottransom/presto#81]
in tutorial,"makezaplist.py Lband.birds",this cmd needs a "birds" file ,but i can't find that in any directory,does it make by "accelsearch" or i need to make one by myself?

**Comment by scottransom** [comment]
You make one yourself based on your data and how much interference you are willing to deal with in the accelsearch output.  That process is described in slides 12 and 13 of the tutorial ("Find the periodic interference" and "Make a 'birds' file").
