### ISSUE TITLE
Scipy does not support histogram anymore -  causes test_fftfit.py to crash

### ISSUE THREAD

**Issue by mserylak** [scottransom/presto#82]
Starting from scipy 1.0.0 scipy.stats.histogram is now deprecated ad removed making it backwards incompatible. Running test_fftfit.py will result in ImportError:

python fftfit_src/test_fftfit.py
Traceback (most recent call last):
  File "fftfit_src/test_fftfit.py", line 12, in <module>
    from psr_utils import gaussian_profile, TWOPI
  File "/home/kat/software/presto/lib/python/psr_utils.py", line 4, in <module>
    from scipy.stats import histogram
ImportError: cannot import name histogram
make: *** [build] Error 1

The best is to use numpy.histogram:

diff --git a/lib/python/psr_utils.py b/lib/python/psr_utils.py
index 99225b8..daffb52 100644
--- a/lib/python/psr_utils.py
+++ b/lib/python/psr_utils.py
@@ -1,7 +1,6 @@
 import numpy as Num
 import numpy.fft as FFT
 import Pgplot, ppgplot, bisect, sinc_interp, parfile
**-from scipy.stats import histogram**
 from scipy.special import ndtr, ndtri, chdtrc, chdtri, fdtr, i0, kolmogorov
 from scipy.optimize import leastsq
 import scipy.optimize.zeros as zeros
@@ -94,7 +93,7 @@ def hist(data, bins, range=None, laby="Number", **kwargs):
                data values are used to define the interval.
     Note:  This command also accepts all the keyword arge of plotbinned().
     """
**-    (ys, lox, dx, out) = histogram(data, bins, range)**
**+    (ys, lox, dx, out) = Num.histogram(data, bins, range)**
     xs = Num.arange(bins, dtype='d')*dx + lox + 0.5*dx
     maxy = int(1.1*max(ys))
     if maxy < max(ys):

Best,
Maciej

**Comment by scottransom** [comment]
Ah-ha!  Thanks for that Maciej!  I'll try to clean this up and patch it today.

**Comment by scottransom** [comment]
I just fixed this.  Thanks for the report!
