### ISSUE TITLE
PRESTO python code not Python3 compatible

### ISSUE THREAD

**Issue by paulray** [scottransom/presto#85]
I recommend updating the python code to be compatible with Python3 as more people are adopting Python3 and are having issues.  Currently, setup.py just gives this misleading error message:
```
% python3 setup.py install --home=${PRESTO}
  File "setup.py", line 44
    raise Exception, "os not supported"
                   ^
SyntaxError: invalid syntax
```

**Comment by sk8forether** [comment]
I am currently working on a project in python3 that will require some updates to certain PRESTO files in [`presto/lib/python`](https://github.com/scottransom/presto/tree/master/lib/python).  If I make decent progress, I may submit a pull request here.  @scottransom Would adding some python3 versions to a new folder, say `presto/lib/python3`, be reasonable?

**Comment by scottransom** [comment]
@sk8forether So I and a few others have been working on this quite a bit recently.  It is a fairly large job.  See this pull request #90.  Try to use that and if you have additional patches, I'll be happy to include them!

**Comment by scottransom** [comment]
Oh, and note that I've been trying to make everything work in both Python 2.7 and 3.X

**Comment by aarchiba** [comment]
See PRs #90 and #72 . 

This and PSRCHIVE seem like the major blockers for pulsar people to make the jump to python 3, so it sure would be nice to see an update.
