### ISSUE TITLE
single_pulse_search.py giving error related to scipy.stats

### ISSUE THREAD

**Issue by wcfiore** [scottransom/presto#86]
Ran into a problem when running single_pulse_search.py on a .singlepulse file- I get a Python error on line 544:
`AttributeError: 'module' object has no attribute 'stats'`
I was able to fix it by just importing scipy.stats in addition to scipy at the beginning of the file, after which single_pulse_search.py runs as normal.

**Comment by scottransom** [comment]
Hmmm.  That's interesting.  I'm not seeing that.  What version of scipy are you using?

**Comment by wcfiore** [comment]
I'm running it on thales at GB, not sure of the version but I didn't do any special python-related things.

**Comment by wcfiore** [comment]
I checked it just now, it's version 0.9.0. I believe that's a version behind?

**Comment by scottransom** [comment]
I just pushed up your recommended fix.  I don't think that breaks anything.  And I fixed it at GB as well.  Thanks for the report!
