### ISSUE TITLE
null pointer in MPI_Bcast during mpiprepsubband

### ISSUE THREAD

**Issue by lyklev** [scottransom/presto#87]
Under certain conditions, ``mpiprepsubband`` terminates with a null pointer error on ``MPI_Bcast``.

The ``MPI_Bcast`` call is in ``mpiprepsubband_utils.c`` line 164. It appears that ``s->start_subint`` and ``s->num_subint`` are not allocated and initialized for rank 0 under certain conditions, when ``s->datatype`` is ``SIGPROCFB``.

Further inspection of the code suggests that in ``sigproc_fb.c``, routine ``read_filterbank_files(..)``, ``s->start_subint`` and ``s->num_subint`` should be allocated and initialized, even if they are not actually used, for example with

```
    s->start_subint = gen_ivect(s->num_files);
    s->num_subint = gen_ivect(s->num_files);
```

**Comment by scottransom** [comment]
Thanks for the report.  I just pushed up your suggested fix for this.  Let me know if you find any other issues!
