### ISSUE TITLE
Using deprecated scipy module in single_pulse_search.py

### ISSUE THREAD

**Issue by bwmeyers** [scottransom/presto#88]
In `single_pulse_search.py` a call to `scipy.stats.histogram` is made, but this has been deprecated since `scipy>=0.17` ([see docs](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.histogram.html)). Apparently the solution is to just use `numpy.histogram` instead.

This causes an `AttributeError` to be raised and thus there are no diagnostic plots created (all the `.singlepulse` files are still written though).

**Comment by scottransom** [comment]
Thanks for the report!  Fixed!  Let me know if you have any other issues.
