### ISSUE TITLE
realfft error

### ISSUE THREAD

**Issue by wcfiore** [scottransom/presto#92]
I have a dedispersed time series which I'm trying to run `realfft` on and it prints this message: 

> realfft() arrays lengths must be evenly divisible by 2.

and it then doesn't write anything to the output .fft file. Any idea what causes this? The .dat and .inf files were created by running `prepdata` on psrfits files. 

Screenshot:

<img width="449" alt="screen shot 2018-07-12 at 7 53 23 pm" src="https://user-images.githubusercontent.com/29396899/42665397-78cf6674-860d-11e8-8942-998c442a6663.png">

**Comment by wcfiore** [comment]
My mistake- I changed the -numout flag on `prepdata` to a more factorable number, it works now!

**Comment by scottransom** [comment]
Ah, great.  Glad you figured it out.  This is something that I'd like to eventually change, but it is slightly tricky (for technical reasons).  But having you mention it puts thinking about it back on my ToDo list!

**Comment by paulray** [comment]
Yeah, prepdata should really call chooseN and spit out a sensible number of points, at least as an option. :-)

**Comment by scottransom** [comment]
Yeah.  I think that is what I will change and make as the default behavior (which can be overwritten using a non-nice number if needed for some reason using -numout).  Should be a pretty easy fix.

**Comment by scottransom** [comment]
The last commit should have fixed this issue, as well as slightly improved the choose_N functions (both in python and C).  Also a new utility function is_power_of_10 in both C and python.
