### ISSUE TITLE
Missing include file

### ISSUE THREAD

**Issue by paulray** [scottransom/presto#93]
https://github.com/scottransom/presto/blob/2a72a7d1b7e6fed805243dd3b954004bb7a80d5a/src/backend_common.c#L7

On many machines, this include causes an error, but it seems not to be necessary, so I recommend just deleting this line.

**Comment by scottransom** [comment]
Strange.  But fixed with your recommendation.  Thanks!

**Comment by paulray** [comment]
Yeah, the equivalent on Macs is
```
#include <mach/error.h>
```
But that may not work on Linux, so deleting was the easiest solution.
