### ISSUE TITLE
Prepfold binary timing bug involving the UNITS line of the ephemeris.

### ISSUE THREAD

**Issue by NickSwainston** [scottransom/presto#95]
I've noticed a bug when using prepfold on binary pulsars with psrcat and long dwell times. If I use the -psr option or give it a ephemeris file using psrcat -e. for example:
[J2145-0750_default.eph.txt](https://github.com/scottransom/presto/files/2523975/J2145-0750_default.eph.txt)
then the resulting plot from prepfold does not time the pulsar correctly:
![1221832280_psr_j2145-0750 pfd](https://user-images.githubusercontent.com/18390846/47630485-09b3b500-db7c-11e8-8f13-d0279dceac75.png)
After some fiddling, I realised that if I remove the last line from the ephemeris as can be seen in the following file:
[J2145-0750_with_no_units.eph.txt](https://github.com/scottransom/presto/files/2523976/J2145-0750_with_no_units.eph.txt)
Then the pulsar is timed correctly:
![1221832280_with_no_units_psr_2145-0750 pfd](https://user-images.githubusercontent.com/18390846/47630504-1e904880-db7c-11e8-9158-971978a7a595.png)
So prepfold doesn't seem to like the line "UNITS           TDB  "

We have noticed this on several different pulsar binaries.

Thank you for your time,
Nick Swainston

**Comment by scottransom** [comment]
No, notice that the missing line is "UNITS TCB",  TEMPO, which prepfold uses when you fold with "-timing" does not recognize the TCB timescale.  The ephemerides need to be in the TDB format.  Luckily there are only a few pulsars in the most recent ATNF database that are in TCB format.

Anyway, given that TEMPO uses TDB to fold the pulsar, I'm surprised that it worked if the epehmeris is really in TCB.  Perhaps it is really in TDB!

**Comment by NickSwainston** [comment]
Sorry, the example I gave does have the units TCB but I have another example where the default units are TDB and the UNITS line still needs to be removed.

With default ephemeris:
[J2222-0137_default.eph.txt](https://github.com/scottransom/presto/files/2527988/J2222-0137_default.eph.txt)
![1221832280_j2222-0137_default pdf](https://user-images.githubusercontent.com/18390846/47695804-cb32fe80-dc3e-11e8-9401-058688830730.png)

With UNITS line removed:
[J2222-0137_with_units_removed.eph.txt](https://github.com/scottransom/presto/files/2527991/J2222-0137_with_units_removed.eph.txt)
![1221832280_j2222-0137_with_units_removed pfd](https://user-images.githubusercontent.com/18390846/47695816-d128df80-dc3e-11e8-9c64-01f7c8bad385.png)

So it may be something stranger than unit conversion, a rounding error perhaps?

**Comment by scottransom** [comment]
I have no clue why that is.  As I said, PRESTO uses TEMPO to generate polycos for folding if you use either "-par" or "-tempo", which it seems like you are doing.  How recent is your install of TEMPO?  I know for a fact that prepfold+TEMPO works when "UNITS TDB" is in the file *and* the ephemeris is in units TDB.  I worry that there are quite a few pulsars in the ATNF database that have incorrect time units.

**Comment by scottransom** [comment]
Actually, in that case I can tell that you folded the pulsar in two different ways.  Note that in one of those, there are binary params given in the prepfold plot.  And in the other, there aren't.  That means that you are folding one of them with -par/-timing and possibly the other with -psr?

Please send me the command lines that you are using.

If you want to fold the data in a way that is useful for timing, you should use:  "prepfold -timing EPHEMERIS.txt INFILE.fits"   And you can use other options like -nsub or -n.

**Comment by NickSwainston** [comment]
I believe you are correct that one of them used the -psr option so I reran all the jobs for clarity.

J2222-0137 Unit TDB
-psr option:                                                              incorrect timing
-par or -timing option using the default ephemeris: correct timing
-par or -timing option removing the unit line:           correct timing

J2145-0750 Unit TCB
-psr option:                                                              incorrect timing
-par or -timing option using the default ephemeris: MJD error, doesn't run
-par or -timing option removing the unit line:           correct timing

What does the -psr option do that is different using an ephemeris file? If the ephemeris works with the units line removed could it be forced to use the TDB units?

**Comment by scottransom** [comment]
So "-psr" does not use the detailed ephemeris.  It uses information that has been downloaded into PRESTO from the ATNF database.  It is useful only for data checking.

If you want to do real timing using the .pfd file, you *must* use  either "-par XXX -nosearch" or "-timing" (which does -nosearch automatically).  That uses TEMPO to compute pulse phase based on the ephemeris.  But since TEMPO does not do TCB, the timing will not be correct if the ephemeris is in TCB but you delete the units line (although you may be able to see the pulsar in the fold).

Hope this helps.

**Comment by NickSwainston** [comment]
So are you saying that when I remove the TCB units, PRESTO should give me incorrect timing but PRESTO is clever enough to work it out or perhaps I got lucky?

**Comment by scottransom** [comment]
If the pulsar is slow (i.e. not precise) enough, so that it is tough to tell the difference between two different clocks that differ by only about 15 parts in a billion, then things will look OK.  For high-precision MSPs, or those in compact orbits, you will see that the folding does *not* do a good job.

**Comment by NickSwainston** [comment]
Alright, that mostly makes sense. Thank you so much for your help and clarification, I appreciate it.
